### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by ghost** [NamelessMC/Nameless-Modules#9]
Another request,

Add a blog style news system so people don't need a main forum to post the news in

**Comment by PikaMug** [comment]
I'd like to see this as a newsfeed-style implementation. Instead of [obvious] categories, have one continuous scrolling feed ordered by date. Let one block of the right sidebar be a timeline separated by month which jumps ahead when clicked, such as:

| January 2022     |
| ------------------- |
| December 2021 |
| October 2021    |
| April 2021 |
| July 2020 |

**Comment by samerton** [comment]
Possible alternative module: https://www.mc-market.org/resources/22772/

**Comment by samerton** [comment]
Closing as above module does a good job of this
